{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled .Values.cnpg.backup.reflector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.backup.existingSecret }}
  labels:
    {{- include "lsp-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    reflector.v1.k8s.emberstack.com/reflects: {{ printf "%s/%s" .Values.cnpg.backup.reflector.sourceNamespace .Values.cnpg.backup.existingSecret | quote }}
type: Opaque
{{- end }}
