{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lsp-indexer.fullname" . }}-docs
  labels:
    {{- include "lsp-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
  {{- with .Values.ingress.docs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lsp-indexer.fullname" . }}-docs
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lsp-indexer.fullname" . }}-graphql
  labels:
    {{- include "lsp-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
  annotations:
    {{- toYaml .Values.ingress.graphql.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /graphql
            pathType: Exact
            backend:
              service:
                name: {{ include "lsp-indexer.fullname" . }}-hasura
                port:
                  name: http
{{- end }}
