#!/bin/sh

if [ -f ./.env ]; then
  . ./.env
  export DB_URL=$DB_URL
  export SQD_GATEWAY=$SQD_GATEWAY
  export RPC_URL=$RPC_URL
  export RPC_RATE_LIMIT=$RPC_RATE_LIMIT
  export FINALITY_CONFIRMATION=$FINALITY_CONFIRMATION
  export IPFS_GATEWAY=$IPFS_GATEWAY
  export FETCH_LIMIT=$FETCH_LIMIT
  export FETCH_BATCH_SIZE=$FETCH_BATCH_SIZE
  export FETCH_RETRY_COUNT=$FETCH_RETRY_COUNT
fi
