/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment V3BlockFields on block {\n    id\n    network\n    chainId: chain_id\n    number\n    hash\n    parentHash: parent_hash\n    timestamp\n  }\n": typeof types.V3BlockFieldsFragmentDoc,
    "\n  fragment V3EventFields on event_fact {\n    id\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    parentHash: parent_hash\n    timestamp: block_timestamp\n    transactionHash: transaction_hash\n    transactionIndex: transaction_index\n    logIndex: log_index\n    address\n    topic0\n    topics\n    data\n    eventName: event_name\n    eventDomain: event_domain\n    decoded\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n": typeof types.V3EventFieldsFragmentDoc,
    "\n  fragment V3ProfileFields on universal_profile {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp3_profile } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    followerCount: followedBy_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: followed_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3ProfileFieldsFragmentDoc,
    "\n  fragment V3DigitalAssetFields on digital_asset {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    standard\n    tokenType: token_type\n    name\n    symbol\n    decimals\n    totalSupply: total_supply\n    tokenIdFormat: token_id_format\n    tokenIdReferenceContract: token_id_reference_contract\n    baseUri: base_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_asset } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    holderCount: ownedAssets_aggregate(where: { balance: { _gt: \"0\" } }) {\n      aggregate {\n        count\n      }\n    }\n    creatorCount: lsp4Creators_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3DigitalAssetFieldsFragmentDoc,
    "\n  fragment V3NftFields on nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    formattedTokenId: formatted_token_id\n    isMinted: is_minted\n    isBurned: is_burned\n    ownerAddress: owner_address\n    tokenUri: token_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_token } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    ownedToken {\n      ownerAddress: owner_address\n      lastBlockNumber: last_block_number\n      universalProfile {\n        ...V3ProfileFields\n      }\n    }\n    chillwhales {\n      chillClaimed: chill_claimed\n      orbsClaimed: orbs_claimed\n      level\n      cooldownExpiry: cooldown_expiry\n      faction\n    }\n  }\n": typeof types.V3NftFieldsFragmentDoc,
    "\n  fragment V3OwnedAssetFields on owned_asset {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    tokenIdCount: tokenIds_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3OwnedAssetFieldsFragmentDoc,
    "\n  fragment V3OwnedTokenFields on owned_token {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    tokenId: token_id\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    nft {\n      ...V3NftFields\n    }\n    ownedAsset {\n      ...V3OwnedAssetFields\n    }\n  }\n": typeof types.V3OwnedTokenFieldsFragmentDoc,
    "\n  fragment V3FollowerFields on follower {\n    id\n    network\n    chainId: chain_id\n    followerAddress: follower_address\n    followedAddress: followed_address\n    isFollowing: is_following\n    followedAt: followed_at\n    unfollowedAt: unfollowed_at\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    followerProfile: followerUniversalProfile {\n      ...V3ProfileFields\n    }\n    followedProfile: followedUniversalProfile {\n      ...V3ProfileFields\n    }\n  }\n": typeof types.V3FollowerFieldsFragmentDoc,
    "\n  fragment V3CreatorFields on lsp4_creator {\n    id\n    network\n    chainId: chain_id\n    assetAddress: asset_address\n    creatorAddress: creator_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    verified\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    creatorProfile {\n      ...V3ProfileFields\n    }\n  }\n": typeof types.V3CreatorFieldsFragmentDoc,
    "\n  fragment V3IssuedAssetFields on lsp12_issued_asset {\n    id\n    network\n    chainId: chain_id\n    issuerAddress: issuer_address\n    assetAddress: asset_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    issuerProfile: universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n": typeof types.V3IssuedAssetFieldsFragmentDoc,
    "\n  fragment V3ControllerFields on lsp6_controller {\n    id\n    network\n    chainId: chain_id\n    profileAddress: profile_address\n    controllerAddress: controller_address\n    arrayIndex: array_index\n    permissions\n    allowedCalls: allowed_calls\n    allowedDataKeys: allowed_data_keys\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    controllerProfile {\n      ...V3ProfileFields\n    }\n  }\n": typeof types.V3ControllerFieldsFragmentDoc,
    "\n  fragment V3ChillwhalesNftFields on chillwhales_nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    chillClaimed: chill_claimed\n    orbsClaimed: orbs_claimed\n    claimCheckAfterBlock: claim_check_after_block\n    level\n    cooldownExpiry: cooldown_expiry\n    faction\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": typeof types.V3ChillwhalesNftFieldsFragmentDoc,
    "\n  fragment V3DataValueFields on data_value {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    dataValue: data_value\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": typeof types.V3DataValueFieldsFragmentDoc,
    "\n  fragment V3MetadataRevisionFields on metadata_revision {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    kind\n    sourceRevision: source_revision\n    contentUri: content_uri\n    contentHash: content_hash\n    contentType: content_type\n    contentLength: content_length\n    content\n    fetchedAt: fetched_at\n    isCurrent: is_current\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": typeof types.V3MetadataRevisionFieldsFragmentDoc,
    "\n  fragment V3IndexedHeadFields on indexed_head {\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    blockTimestamp: block_timestamp\n    finalizedBlockNumber: finalized_block_number\n    finalizedBlockHash: finalized_block_hash\n    updatedAt: updated_at\n  }\n": typeof types.V3IndexedHeadFieldsFragmentDoc,
    "\n  query V3Blocks($where: block_bool_exp, $orderBy: [block_order_by!], $limit: Int, $offset: Int) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n    total: block_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3BlocksDocument,
    "\n  subscription V3BlocksSubscription(\n    $where: block_bool_exp\n    $orderBy: [block_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n  }\n": typeof types.V3BlocksSubscriptionDocument,
    "\n  query V3Events(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n    total: event_fact_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3EventsDocument,
    "\n  subscription V3EventsSubscription(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n  }\n": typeof types.V3EventsSubscriptionDocument,
    "\n  query V3UniversalProfiles(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n    total: universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3UniversalProfilesDocument,
    "\n  subscription V3UniversalProfilesSubscription(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n  }\n": typeof types.V3UniversalProfilesSubscriptionDocument,
    "\n  query V3DigitalAssets(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n    total: digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3DigitalAssetsDocument,
    "\n  subscription V3DigitalAssetsSubscription(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n  }\n": typeof types.V3DigitalAssetsSubscriptionDocument,
    "\n  query V3Nfts($where: nft_bool_exp, $orderBy: [nft_order_by!], $limit: Int, $offset: Int) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n    total: nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3NftsDocument,
    "\n  subscription V3NftsSubscription(\n    $where: nft_bool_exp\n    $orderBy: [nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n  }\n": typeof types.V3NftsSubscriptionDocument,
    "\n  query V3OwnedAssets(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n    total: owned_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3OwnedAssetsDocument,
    "\n  subscription V3OwnedAssetsSubscription(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n  }\n": typeof types.V3OwnedAssetsSubscriptionDocument,
    "\n  query V3OwnedTokens(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n    total: owned_token_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3OwnedTokensDocument,
    "\n  subscription V3OwnedTokensSubscription(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n  }\n": typeof types.V3OwnedTokensSubscriptionDocument,
    "\n  query V3Followers(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n    total: follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3FollowersDocument,
    "\n  subscription V3FollowersSubscription(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n  }\n": typeof types.V3FollowersSubscriptionDocument,
    "\n  query V3Creators(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n    total: lsp4_creator_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3CreatorsDocument,
    "\n  subscription V3CreatorsSubscription(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n  }\n": typeof types.V3CreatorsSubscriptionDocument,
    "\n  query V3IssuedAssets(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n    total: lsp12_issued_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3IssuedAssetsDocument,
    "\n  subscription V3IssuedAssetsSubscription(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n  }\n": typeof types.V3IssuedAssetsSubscriptionDocument,
    "\n  query V3Controllers(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n    total: lsp6_controller_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3ControllersDocument,
    "\n  subscription V3ControllersSubscription(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n  }\n": typeof types.V3ControllersSubscriptionDocument,
    "\n  query V3ChillwhalesNfts(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n    total: chillwhales_nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3ChillwhalesNftsDocument,
    "\n  subscription V3ChillwhalesNftsSubscription(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n  }\n": typeof types.V3ChillwhalesNftsSubscriptionDocument,
    "\n  query V3DataValues(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n    total: data_value_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3DataValuesDocument,
    "\n  subscription V3DataValuesSubscription(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n  }\n": typeof types.V3DataValuesSubscriptionDocument,
    "\n  query V3MetadataRevisions(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n    total: metadata_revision_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3MetadataRevisionsDocument,
    "\n  subscription V3MetadataRevisionsSubscription(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n  }\n": typeof types.V3MetadataRevisionsSubscriptionDocument,
    "\n  query V3IndexedHeads(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n    total: indexed_head_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.V3IndexedHeadsDocument,
    "\n  subscription V3IndexedHeadsSubscription(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n  }\n": typeof types.V3IndexedHeadsSubscriptionDocument,
};
const documents: Documents = {
    "\n  fragment V3BlockFields on block {\n    id\n    network\n    chainId: chain_id\n    number\n    hash\n    parentHash: parent_hash\n    timestamp\n  }\n": types.V3BlockFieldsFragmentDoc,
    "\n  fragment V3EventFields on event_fact {\n    id\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    parentHash: parent_hash\n    timestamp: block_timestamp\n    transactionHash: transaction_hash\n    transactionIndex: transaction_index\n    logIndex: log_index\n    address\n    topic0\n    topics\n    data\n    eventName: event_name\n    eventDomain: event_domain\n    decoded\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n": types.V3EventFieldsFragmentDoc,
    "\n  fragment V3ProfileFields on universal_profile {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp3_profile } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    followerCount: followedBy_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: followed_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3ProfileFieldsFragmentDoc,
    "\n  fragment V3DigitalAssetFields on digital_asset {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    standard\n    tokenType: token_type\n    name\n    symbol\n    decimals\n    totalSupply: total_supply\n    tokenIdFormat: token_id_format\n    tokenIdReferenceContract: token_id_reference_contract\n    baseUri: base_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_asset } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    holderCount: ownedAssets_aggregate(where: { balance: { _gt: \"0\" } }) {\n      aggregate {\n        count\n      }\n    }\n    creatorCount: lsp4Creators_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3DigitalAssetFieldsFragmentDoc,
    "\n  fragment V3NftFields on nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    formattedTokenId: formatted_token_id\n    isMinted: is_minted\n    isBurned: is_burned\n    ownerAddress: owner_address\n    tokenUri: token_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_token } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    ownedToken {\n      ownerAddress: owner_address\n      lastBlockNumber: last_block_number\n      universalProfile {\n        ...V3ProfileFields\n      }\n    }\n    chillwhales {\n      chillClaimed: chill_claimed\n      orbsClaimed: orbs_claimed\n      level\n      cooldownExpiry: cooldown_expiry\n      faction\n    }\n  }\n": types.V3NftFieldsFragmentDoc,
    "\n  fragment V3OwnedAssetFields on owned_asset {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    tokenIdCount: tokenIds_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3OwnedAssetFieldsFragmentDoc,
    "\n  fragment V3OwnedTokenFields on owned_token {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    tokenId: token_id\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    nft {\n      ...V3NftFields\n    }\n    ownedAsset {\n      ...V3OwnedAssetFields\n    }\n  }\n": types.V3OwnedTokenFieldsFragmentDoc,
    "\n  fragment V3FollowerFields on follower {\n    id\n    network\n    chainId: chain_id\n    followerAddress: follower_address\n    followedAddress: followed_address\n    isFollowing: is_following\n    followedAt: followed_at\n    unfollowedAt: unfollowed_at\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    followerProfile: followerUniversalProfile {\n      ...V3ProfileFields\n    }\n    followedProfile: followedUniversalProfile {\n      ...V3ProfileFields\n    }\n  }\n": types.V3FollowerFieldsFragmentDoc,
    "\n  fragment V3CreatorFields on lsp4_creator {\n    id\n    network\n    chainId: chain_id\n    assetAddress: asset_address\n    creatorAddress: creator_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    verified\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    creatorProfile {\n      ...V3ProfileFields\n    }\n  }\n": types.V3CreatorFieldsFragmentDoc,
    "\n  fragment V3IssuedAssetFields on lsp12_issued_asset {\n    id\n    network\n    chainId: chain_id\n    issuerAddress: issuer_address\n    assetAddress: asset_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    issuerProfile: universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n": types.V3IssuedAssetFieldsFragmentDoc,
    "\n  fragment V3ControllerFields on lsp6_controller {\n    id\n    network\n    chainId: chain_id\n    profileAddress: profile_address\n    controllerAddress: controller_address\n    arrayIndex: array_index\n    permissions\n    allowedCalls: allowed_calls\n    allowedDataKeys: allowed_data_keys\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    controllerProfile {\n      ...V3ProfileFields\n    }\n  }\n": types.V3ControllerFieldsFragmentDoc,
    "\n  fragment V3ChillwhalesNftFields on chillwhales_nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    chillClaimed: chill_claimed\n    orbsClaimed: orbs_claimed\n    claimCheckAfterBlock: claim_check_after_block\n    level\n    cooldownExpiry: cooldown_expiry\n    faction\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": types.V3ChillwhalesNftFieldsFragmentDoc,
    "\n  fragment V3DataValueFields on data_value {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    dataValue: data_value\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": types.V3DataValueFieldsFragmentDoc,
    "\n  fragment V3MetadataRevisionFields on metadata_revision {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    kind\n    sourceRevision: source_revision\n    contentUri: content_uri\n    contentHash: content_hash\n    contentType: content_type\n    contentLength: content_length\n    content\n    fetchedAt: fetched_at\n    isCurrent: is_current\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n": types.V3MetadataRevisionFieldsFragmentDoc,
    "\n  fragment V3IndexedHeadFields on indexed_head {\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    blockTimestamp: block_timestamp\n    finalizedBlockNumber: finalized_block_number\n    finalizedBlockHash: finalized_block_hash\n    updatedAt: updated_at\n  }\n": types.V3IndexedHeadFieldsFragmentDoc,
    "\n  query V3Blocks($where: block_bool_exp, $orderBy: [block_order_by!], $limit: Int, $offset: Int) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n    total: block_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3BlocksDocument,
    "\n  subscription V3BlocksSubscription(\n    $where: block_bool_exp\n    $orderBy: [block_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n  }\n": types.V3BlocksSubscriptionDocument,
    "\n  query V3Events(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n    total: event_fact_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3EventsDocument,
    "\n  subscription V3EventsSubscription(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n  }\n": types.V3EventsSubscriptionDocument,
    "\n  query V3UniversalProfiles(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n    total: universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3UniversalProfilesDocument,
    "\n  subscription V3UniversalProfilesSubscription(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n  }\n": types.V3UniversalProfilesSubscriptionDocument,
    "\n  query V3DigitalAssets(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n    total: digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3DigitalAssetsDocument,
    "\n  subscription V3DigitalAssetsSubscription(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n  }\n": types.V3DigitalAssetsSubscriptionDocument,
    "\n  query V3Nfts($where: nft_bool_exp, $orderBy: [nft_order_by!], $limit: Int, $offset: Int) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n    total: nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3NftsDocument,
    "\n  subscription V3NftsSubscription(\n    $where: nft_bool_exp\n    $orderBy: [nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n  }\n": types.V3NftsSubscriptionDocument,
    "\n  query V3OwnedAssets(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n    total: owned_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3OwnedAssetsDocument,
    "\n  subscription V3OwnedAssetsSubscription(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n  }\n": types.V3OwnedAssetsSubscriptionDocument,
    "\n  query V3OwnedTokens(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n    total: owned_token_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3OwnedTokensDocument,
    "\n  subscription V3OwnedTokensSubscription(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n  }\n": types.V3OwnedTokensSubscriptionDocument,
    "\n  query V3Followers(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n    total: follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3FollowersDocument,
    "\n  subscription V3FollowersSubscription(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n  }\n": types.V3FollowersSubscriptionDocument,
    "\n  query V3Creators(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n    total: lsp4_creator_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3CreatorsDocument,
    "\n  subscription V3CreatorsSubscription(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n  }\n": types.V3CreatorsSubscriptionDocument,
    "\n  query V3IssuedAssets(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n    total: lsp12_issued_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3IssuedAssetsDocument,
    "\n  subscription V3IssuedAssetsSubscription(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n  }\n": types.V3IssuedAssetsSubscriptionDocument,
    "\n  query V3Controllers(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n    total: lsp6_controller_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3ControllersDocument,
    "\n  subscription V3ControllersSubscription(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n  }\n": types.V3ControllersSubscriptionDocument,
    "\n  query V3ChillwhalesNfts(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n    total: chillwhales_nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3ChillwhalesNftsDocument,
    "\n  subscription V3ChillwhalesNftsSubscription(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n  }\n": types.V3ChillwhalesNftsSubscriptionDocument,
    "\n  query V3DataValues(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n    total: data_value_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3DataValuesDocument,
    "\n  subscription V3DataValuesSubscription(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n  }\n": types.V3DataValuesSubscriptionDocument,
    "\n  query V3MetadataRevisions(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n    total: metadata_revision_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3MetadataRevisionsDocument,
    "\n  subscription V3MetadataRevisionsSubscription(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n  }\n": types.V3MetadataRevisionsSubscriptionDocument,
    "\n  query V3IndexedHeads(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n    total: indexed_head_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.V3IndexedHeadsDocument,
    "\n  subscription V3IndexedHeadsSubscription(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n  }\n": types.V3IndexedHeadsSubscriptionDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3BlockFields on block {\n    id\n    network\n    chainId: chain_id\n    number\n    hash\n    parentHash: parent_hash\n    timestamp\n  }\n"): typeof import('./graphql').V3BlockFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3EventFields on event_fact {\n    id\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    parentHash: parent_hash\n    timestamp: block_timestamp\n    transactionHash: transaction_hash\n    transactionIndex: transaction_index\n    logIndex: log_index\n    address\n    topic0\n    topics\n    data\n    eventName: event_name\n    eventDomain: event_domain\n    decoded\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n"): typeof import('./graphql').V3EventFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3ProfileFields on universal_profile {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp3_profile } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    followerCount: followedBy_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: followed_aggregate(where: { is_following: { _eq: true } }) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3ProfileFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3DigitalAssetFields on digital_asset {\n    id\n    network\n    chainId: chain_id\n    address\n    ownerAddress: owner_address\n    standard\n    tokenType: token_type\n    name\n    symbol\n    decimals\n    totalSupply: total_supply\n    tokenIdFormat: token_id_format\n    tokenIdReferenceContract: token_id_reference_contract\n    baseUri: base_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_asset } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    holderCount: ownedAssets_aggregate(where: { balance: { _gt: \"0\" } }) {\n      aggregate {\n        count\n      }\n    }\n    creatorCount: lsp4Creators_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3DigitalAssetFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3NftFields on nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    formattedTokenId: formatted_token_id\n    isMinted: is_minted\n    isBurned: is_burned\n    ownerAddress: owner_address\n    tokenUri: token_uri\n    verification\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    metadataRevisions(\n      where: { kind: { _eq: lsp4_token } }\n      order_by: [{ last_block_number: desc }, { chain_id: asc }, { id: asc }]\n      limit: 1\n    ) {\n      content\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    ownedToken {\n      ownerAddress: owner_address\n      lastBlockNumber: last_block_number\n      universalProfile {\n        ...V3ProfileFields\n      }\n    }\n    chillwhales {\n      chillClaimed: chill_claimed\n      orbsClaimed: orbs_claimed\n      level\n      cooldownExpiry: cooldown_expiry\n      faction\n    }\n  }\n"): typeof import('./graphql').V3NftFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3OwnedAssetFields on owned_asset {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    tokenIdCount: tokenIds_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3OwnedAssetFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3OwnedTokenFields on owned_token {\n    id\n    network\n    chainId: chain_id\n    ownerAddress: owner_address\n    assetAddress: asset_address\n    tokenId: token_id\n    balance\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    universalProfile {\n      ...V3ProfileFields\n    }\n    nft {\n      ...V3NftFields\n    }\n    ownedAsset {\n      ...V3OwnedAssetFields\n    }\n  }\n"): typeof import('./graphql').V3OwnedTokenFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3FollowerFields on follower {\n    id\n    network\n    chainId: chain_id\n    followerAddress: follower_address\n    followedAddress: followed_address\n    isFollowing: is_following\n    followedAt: followed_at\n    unfollowedAt: unfollowed_at\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    followerProfile: followerUniversalProfile {\n      ...V3ProfileFields\n    }\n    followedProfile: followedUniversalProfile {\n      ...V3ProfileFields\n    }\n  }\n"): typeof import('./graphql').V3FollowerFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3CreatorFields on lsp4_creator {\n    id\n    network\n    chainId: chain_id\n    assetAddress: asset_address\n    creatorAddress: creator_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    verified\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    creatorProfile {\n      ...V3ProfileFields\n    }\n  }\n"): typeof import('./graphql').V3CreatorFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3IssuedAssetFields on lsp12_issued_asset {\n    id\n    network\n    chainId: chain_id\n    issuerAddress: issuer_address\n    assetAddress: asset_address\n    arrayIndex: array_index\n    interfaceId: interface_id\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    issuerProfile: universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n  }\n"): typeof import('./graphql').V3IssuedAssetFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3ControllerFields on lsp6_controller {\n    id\n    network\n    chainId: chain_id\n    profileAddress: profile_address\n    controllerAddress: controller_address\n    arrayIndex: array_index\n    permissions\n    allowedCalls: allowed_calls\n    allowedDataKeys: allowed_data_keys\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    controllerProfile {\n      ...V3ProfileFields\n    }\n  }\n"): typeof import('./graphql').V3ControllerFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3ChillwhalesNftFields on chillwhales_nft {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    chillClaimed: chill_claimed\n    orbsClaimed: orbs_claimed\n    claimCheckAfterBlock: claim_check_after_block\n    level\n    cooldownExpiry: cooldown_expiry\n    faction\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n"): typeof import('./graphql').V3ChillwhalesNftFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3DataValueFields on data_value {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    dataValue: data_value\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n"): typeof import('./graphql').V3DataValueFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3MetadataRevisionFields on metadata_revision {\n    id\n    network\n    chainId: chain_id\n    address\n    tokenId: token_id\n    dataKey: data_key\n    kind\n    sourceRevision: source_revision\n    contentUri: content_uri\n    contentHash: content_hash\n    contentType: content_type\n    contentLength: content_length\n    content\n    fetchedAt: fetched_at\n    isCurrent: is_current\n    lastBlockNumber: last_block_number\n    lastBlockHash: last_block_hash\n    lastTransactionHash: last_transaction_hash\n    lastTransactionIndex: last_transaction_index\n    lastLogIndex: last_log_index\n    universalProfile {\n      ...V3ProfileFields\n    }\n    digitalAsset {\n      ...V3DigitalAssetFields\n    }\n    nft {\n      ...V3NftFields\n    }\n  }\n"): typeof import('./graphql').V3MetadataRevisionFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment V3IndexedHeadFields on indexed_head {\n    network\n    chainId: chain_id\n    blockNumber: block_number\n    blockHash: block_hash\n    blockTimestamp: block_timestamp\n    finalizedBlockNumber: finalized_block_number\n    finalizedBlockHash: finalized_block_hash\n    updatedAt: updated_at\n  }\n"): typeof import('./graphql').V3IndexedHeadFieldsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Blocks($where: block_bool_exp, $orderBy: [block_order_by!], $limit: Int, $offset: Int) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n    total: block_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3BlocksDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3BlocksSubscription(\n    $where: block_bool_exp\n    $orderBy: [block_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: block(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3BlockFields\n    }\n  }\n"): typeof import('./graphql').V3BlocksSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Events(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n    total: event_fact_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3EventsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3EventsSubscription(\n    $where: event_fact_bool_exp\n    $orderBy: [event_fact_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: event_fact(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3EventFields\n    }\n  }\n"): typeof import('./graphql').V3EventsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3UniversalProfiles(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n    total: universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3UniversalProfilesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3UniversalProfilesSubscription(\n    $where: universal_profile_bool_exp\n    $orderBy: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: universal_profile(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ProfileFields\n    }\n  }\n"): typeof import('./graphql').V3UniversalProfilesSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3DigitalAssets(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n    total: digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3DigitalAssetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3DigitalAssetsSubscription(\n    $where: digital_asset_bool_exp\n    $orderBy: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: digital_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DigitalAssetFields\n    }\n  }\n"): typeof import('./graphql').V3DigitalAssetsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Nfts($where: nft_bool_exp, $orderBy: [nft_order_by!], $limit: Int, $offset: Int) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n    total: nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3NftsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3NftsSubscription(\n    $where: nft_bool_exp\n    $orderBy: [nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3NftFields\n    }\n  }\n"): typeof import('./graphql').V3NftsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3OwnedAssets(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n    total: owned_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3OwnedAssetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3OwnedAssetsSubscription(\n    $where: owned_asset_bool_exp\n    $orderBy: [owned_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedAssetFields\n    }\n  }\n"): typeof import('./graphql').V3OwnedAssetsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3OwnedTokens(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n    total: owned_token_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3OwnedTokensDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3OwnedTokensSubscription(\n    $where: owned_token_bool_exp\n    $orderBy: [owned_token_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: owned_token(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3OwnedTokenFields\n    }\n  }\n"): typeof import('./graphql').V3OwnedTokensSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Followers(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n    total: follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3FollowersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3FollowersSubscription(\n    $where: follower_bool_exp\n    $orderBy: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: follower(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3FollowerFields\n    }\n  }\n"): typeof import('./graphql').V3FollowersSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Creators(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n    total: lsp4_creator_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3CreatorsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3CreatorsSubscription(\n    $where: lsp4_creator_bool_exp\n    $orderBy: [lsp4_creator_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp4_creator(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3CreatorFields\n    }\n  }\n"): typeof import('./graphql').V3CreatorsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3IssuedAssets(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n    total: lsp12_issued_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3IssuedAssetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3IssuedAssetsSubscription(\n    $where: lsp12_issued_asset_bool_exp\n    $orderBy: [lsp12_issued_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp12_issued_asset(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IssuedAssetFields\n    }\n  }\n"): typeof import('./graphql').V3IssuedAssetsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3Controllers(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n    total: lsp6_controller_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3ControllersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3ControllersSubscription(\n    $where: lsp6_controller_bool_exp\n    $orderBy: [lsp6_controller_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: lsp6_controller(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ControllerFields\n    }\n  }\n"): typeof import('./graphql').V3ControllersSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3ChillwhalesNfts(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n    total: chillwhales_nft_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3ChillwhalesNftsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3ChillwhalesNftsSubscription(\n    $where: chillwhales_nft_bool_exp\n    $orderBy: [chillwhales_nft_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: chillwhales_nft(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3ChillwhalesNftFields\n    }\n  }\n"): typeof import('./graphql').V3ChillwhalesNftsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3DataValues(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n    total: data_value_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3DataValuesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3DataValuesSubscription(\n    $where: data_value_bool_exp\n    $orderBy: [data_value_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: data_value(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3DataValueFields\n    }\n  }\n"): typeof import('./graphql').V3DataValuesSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3MetadataRevisions(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n    total: metadata_revision_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3MetadataRevisionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3MetadataRevisionsSubscription(\n    $where: metadata_revision_bool_exp\n    $orderBy: [metadata_revision_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: metadata_revision(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3MetadataRevisionFields\n    }\n  }\n"): typeof import('./graphql').V3MetadataRevisionsSubscriptionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query V3IndexedHeads(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n    total: indexed_head_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').V3IndexedHeadsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription V3IndexedHeadsSubscription(\n    $where: indexed_head_bool_exp\n    $orderBy: [indexed_head_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    items: indexed_head(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {\n      ...V3IndexedHeadFields\n    }\n  }\n"): typeof import('./graphql').V3IndexedHeadsSubscriptionDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
