/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetDataChangedEvents(\n    $where: data_changed_bool_exp\n    $order_by: [data_changed_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    data_changed(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      data_key\n      data_value\n      block_number\n      log_index\n      transaction_index\n      timestamp\n    }\n    data_changed_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetDataChangedEventsDocument,
    "\n  query GetDigitalAsset($where: digital_asset_bool_exp!) {\n    digital_asset(where: $where, limit: 1) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": typeof types.GetDigitalAssetDocument,
    "\n  query GetDigitalAssets(\n    $where: digital_asset_bool_exp\n    $order_by: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    digital_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetDigitalAssetsDocument,
    "\n  query GetEncryptedAsset($where: lsp29_encrypted_asset_bool_exp!) {\n    lsp29_encrypted_asset(where: $where, limit: 1) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": typeof types.GetEncryptedAssetDocument,
    "\n  query GetEncryptedAssets(\n    $where: lsp29_encrypted_asset_bool_exp\n    $order_by: [lsp29_encrypted_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    lsp29_encrypted_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    lsp29_encrypted_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetEncryptedAssetsDocument,
    "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": typeof types.GetProfileDocument,
    "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetProfilesDocument,
    "\n  query GetFollowers(\n    $where: follower_bool_exp\n    $order_by: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    follower(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      follower_address\n      followed_address\n    }\n    follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetFollowersDocument,
    "\n  query GetFollowCount($followerWhere: follower_bool_exp, $followingWhere: follower_bool_exp) {\n    followerCount: follower_aggregate(where: $followerWhere) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: follower_aggregate(where: $followingWhere) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetFollowCountDocument,
    "\n  query GetUniversalReceiverEvents(\n    $where: universal_receiver_bool_exp\n    $order_by: [universal_receiver_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    universal_receiver(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      from\n      type_id\n      received_data\n      returned_value\n      block_number\n      transaction_index\n      log_index\n      value\n      timestamp\n    }\n    universal_receiver_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetUniversalReceiverEventsDocument,
};
const documents: Documents = {
    "\n  query GetDataChangedEvents(\n    $where: data_changed_bool_exp\n    $order_by: [data_changed_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    data_changed(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      data_key\n      data_value\n      block_number\n      log_index\n      transaction_index\n      timestamp\n    }\n    data_changed_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetDataChangedEventsDocument,
    "\n  query GetDigitalAsset($where: digital_asset_bool_exp!) {\n    digital_asset(where: $where, limit: 1) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": types.GetDigitalAssetDocument,
    "\n  query GetDigitalAssets(\n    $where: digital_asset_bool_exp\n    $order_by: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    digital_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetDigitalAssetsDocument,
    "\n  query GetEncryptedAsset($where: lsp29_encrypted_asset_bool_exp!) {\n    lsp29_encrypted_asset(where: $where, limit: 1) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": types.GetEncryptedAssetDocument,
    "\n  query GetEncryptedAssets(\n    $where: lsp29_encrypted_asset_bool_exp\n    $order_by: [lsp29_encrypted_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    lsp29_encrypted_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    lsp29_encrypted_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetEncryptedAssetsDocument,
    "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": types.GetProfileDocument,
    "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetProfilesDocument,
    "\n  query GetFollowers(\n    $where: follower_bool_exp\n    $order_by: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    follower(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      follower_address\n      followed_address\n    }\n    follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetFollowersDocument,
    "\n  query GetFollowCount($followerWhere: follower_bool_exp, $followingWhere: follower_bool_exp) {\n    followerCount: follower_aggregate(where: $followerWhere) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: follower_aggregate(where: $followingWhere) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetFollowCountDocument,
    "\n  query GetUniversalReceiverEvents(\n    $where: universal_receiver_bool_exp\n    $order_by: [universal_receiver_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    universal_receiver(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      from\n      type_id\n      received_data\n      returned_value\n      block_number\n      transaction_index\n      log_index\n      value\n      timestamp\n    }\n    universal_receiver_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetUniversalReceiverEventsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDataChangedEvents(\n    $where: data_changed_bool_exp\n    $order_by: [data_changed_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    data_changed(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      data_key\n      data_value\n      block_number\n      log_index\n      transaction_index\n      timestamp\n    }\n    data_changed_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetDataChangedEventsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDigitalAsset($where: digital_asset_bool_exp!) {\n    digital_asset(where: $where, limit: 1) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDigitalAssetDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDigitalAssets(\n    $where: digital_asset_bool_exp\n    $order_by: [digital_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    digital_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp4TokenName {\n        value\n      }\n      lsp4TokenSymbol {\n        value\n      }\n      lsp4TokenType {\n        value\n      }\n      totalSupply {\n        value\n      }\n      lsp4Creators_aggregate {\n        aggregate {\n          count\n        }\n      }\n      ownedTokens_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    digital_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetDigitalAssetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEncryptedAsset($where: lsp29_encrypted_asset_bool_exp!) {\n    lsp29_encrypted_asset(where: $where, limit: 1) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetEncryptedAssetDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEncryptedAssets(\n    $where: lsp29_encrypted_asset_bool_exp\n    $order_by: [lsp29_encrypted_asset_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    lsp29_encrypted_asset(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      url\n      content_id\n      is_data_fetched\n      version\n      timestamp\n      universal_profile_id\n      title {\n        value\n      }\n      description {\n        value\n      }\n      file {\n        name\n        type\n        size\n      }\n      encryption {\n        method\n      }\n      images {\n        url\n        width\n        height\n      }\n      images_aggregate {\n        aggregate {\n          count\n        }\n      }\n    }\n    lsp29_encrypted_asset_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetEncryptedAssetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetProfileDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetProfilesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFollowers(\n    $where: follower_bool_exp\n    $order_by: [follower_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    follower(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      follower_address\n      followed_address\n    }\n    follower_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetFollowersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFollowCount($followerWhere: follower_bool_exp, $followingWhere: follower_bool_exp) {\n    followerCount: follower_aggregate(where: $followerWhere) {\n      aggregate {\n        count\n      }\n    }\n    followingCount: follower_aggregate(where: $followingWhere) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetFollowCountDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUniversalReceiverEvents(\n    $where: universal_receiver_bool_exp\n    $order_by: [universal_receiver_order_by!]\n    $limit: Int\n    $offset: Int\n  ) {\n    universal_receiver(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      from\n      type_id\n      received_data\n      returned_value\n      block_number\n      transaction_index\n      log_index\n      value\n      timestamp\n    }\n    universal_receiver_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetUniversalReceiverEventsDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
