/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": typeof types.GetProfileDocument,
    "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": typeof types.GetProfilesDocument,
};
const documents: Documents = {
    "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n": types.GetProfileDocument,
    "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n": types.GetProfilesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProfile(\n    $where: universal_profile_bool_exp!\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, limit: 1) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetProfileDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProfiles(\n    $where: universal_profile_bool_exp\n    $order_by: [universal_profile_order_by!]\n    $limit: Int\n    $offset: Int\n    $includeName: Boolean! = true\n    $includeDescription: Boolean! = true\n    $includeTags: Boolean! = true\n    $includeLinks: Boolean! = true\n    $includeAvatar: Boolean! = true\n    $includeProfileImage: Boolean! = true\n    $includeBackgroundImage: Boolean! = true\n    $includeFollowerCount: Boolean! = true\n    $includeFollowingCount: Boolean! = true\n  ) {\n    universal_profile(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {\n      id\n      address\n      lsp3Profile {\n        name @include(if: $includeName) {\n          value\n        }\n        description @include(if: $includeDescription) {\n          value\n        }\n        tags @include(if: $includeTags) {\n          value\n        }\n        links @include(if: $includeLinks) {\n          title\n          url\n        }\n        avatar @include(if: $includeAvatar) {\n          url\n          file_type\n          verification_method\n          verification_data\n        }\n        profileImage @include(if: $includeProfileImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n        backgroundImage @include(if: $includeBackgroundImage) {\n          url\n          width\n          height\n          verification_method\n          verification_data\n        }\n      }\n      followedBy_aggregate @include(if: $includeFollowerCount) {\n        aggregate {\n          count\n        }\n      }\n      followed_aggregate @include(if: $includeFollowingCount) {\n        aggregate {\n          count\n        }\n      }\n    }\n    universal_profile_aggregate(where: $where) {\n      aggregate {\n        count\n      }\n    }\n  }\n"): typeof import('./graphql').GetProfilesDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
