name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: kethalia/workflows/.github/workflows/release-changesets.yml@v4
    with:
      publish-command: pnpm ci:publish
      setup-command: pnpm build
      pr-title: "chore: version packages"
      commit-message: "chore: version packages"
    secrets: inherit
